
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'First floor',220,101, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'First floor',220,102, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'First floor',220,103, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'First floor',220,104, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'First floor',220,105, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'First floor',220,106, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'First floor',220,107, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single ',0, 'Disabled room', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'First floor',240,108, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single ',0, 'Disabled room', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'First floor',240,109, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Disabled room', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'First floor',380,110, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'First floor',380,111, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'First floor',380,112, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'First floor',220,113, '2 single bed')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'First floor',220,114, '2 single bed')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'First floor',380,115, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'First floor',380,116, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',2, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'First floor',380,117, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',2, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'First floor',380,118, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),4, '2 x Double ',2, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'First floor',550,119, '2 Double bed, 1 single bed, 1 baby bed')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Second floor',220,201, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Second floor',220,202, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Second floor',220,203, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Second floor',220,204, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Second floor',220,205, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Second floor',220,206, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Second floor',220,207, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single ',0, 'Disabled room', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'Second floor',240,208, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single ',0, 'Disabled room', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'Second floor',240,209, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Disabled room', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Second floor',380,210, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Second floor',380,211, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Second floor',380,212, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Second floor',220,213, '2 single bed')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Second floor',220,214, '2 single bed')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Second floor',380,215, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Second floor',380,216, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',2, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Second floor',380,217, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),4, '2 x Double ',2, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Second floor',550,218, '2 Double bed, 1 single bed, 1 baby bed')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',2, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Second floor',380,219, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Third floor',220,301, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Third floor',220,302, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Third floor',220,303, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Third floor',220,304, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Third floor',220,305, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Third floor',220,306, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Third floor',220,307, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single ',0, 'Disabled room', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'Third floor',240,308, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single ',0, 'Disabled room', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'Third floor',240,309, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Disabled room', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'Third floor',240,310, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'Third floor',240,311, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'Third floor',240,312, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Third floor',220,313, '2 single bed')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Third floor',220,314, '2 single bed')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),4, '2 x Double ',2, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Third floor',550,315, '2 Double bed, 1 single bed, 1 baby bed')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',1, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Third floor',380,316, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',2, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Third floor',380,317, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',2, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Third floor',380,318, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',2, 'Non Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Third floor',380,319, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',0, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Fourth floor',220,401, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',0, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Fourth floor',220,402, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',0, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Fourth floor',220,403, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Fourth floor',220,404, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Fourth floor',220,405, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Fourth floor',220,406, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single',1, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Fourth floor',220,407, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single ',0, 'Disabled room', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'Fourth floor',240,408, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),1, 'Single ',0, 'Disabled room', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'Fourth floor',240,409, 'Single ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Disabled room', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'Fourth floor',240,410, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'Fourth floor',240,411, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine', 'Fourth floor',240,412, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Fourth floor',220,413, '2 single bed')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',0, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler', 'Fourth floor',220,414, '2 single bed')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',1, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Fourth floor',380,415, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',1, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Fourth floor',380,416, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),2, 'Double ',2, 'Smoking', 'mini fridge, TV, Airco,WIFI, toilet, shower + bathtub, phone, water boiler, coffee machine', 'Fourth floor',380,417, 'Double bed ')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),8, 'Penthouse',2, 'Smoking', 'Mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine, Sauna, Bathtub, swimming pool ', 'Fourth floor',800,418, '2 x Double bed, 4 single beds, 2 baby beds')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),8, 'Penthouse',2, 'Smoking', 'Mini fridge, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine, Sauna, Bathtub, swimming pool ', 'Fourth floor',800,419, '2 x Double bed, 4 single beds, 2 baby beds')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),10, 'Penthouse',2, 'Smoking', 'Kitchen, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine, Sauna, Bathtub, infinity swimming pool, terras, parasols, terras chairs en tables ', 'Fifth floor',3000,501, '3 x Double bed, 4 single beds, 2 baby beds')
INSERT INTO room VALUES (NEXTVAL('ROOM_SEQ'),10, 'Penthouse',2, 'Smoking', 'Kitchen, TV, Airco,WIFI, toilet, shower, phone, water boiler, coffee machine, Sauna, Bathtub, infinity swimming pool, terras, parasols, terras chairs en tables ', 'Fifth floor',3000,502, '3 x Double bed, 4 single beds, 2 baby beds')